# Generated by Django 3.1.1 on 2020-10-12 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic_posts'),
            preserve_default=False,
        ),
    ]
