# Generated by Django 3.1.1 on 2020-10-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_pic',
        ),
    ]
